remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-include-cache
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Camilo Torres Mestra - elsolarpunketo
description: The brief intersticial space between tech and philosophy.